//GETS
export const GET_COUNTRIES = "GET_COUNTRIES"
export const GET_DETAIL = "GET_DETAIL"
export const RESET = "RESET"
export const GET_NAME = "GET_NAME"
//FILTER CONTINENTS
export const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT"
export const ALL_OCEANIA = "Oceania"
export const ALL_EUROPE = "Europe"
export const ALL_ASIA = "Asia"
export const ALL_AFRICA ="Africa"
export const ALL_ANTARTICA = "Antarctica"
export const ALL_AMERICA_S ="South America"
export const ALL_AMERICA_N ="North America"
export const WORLD = "WORLD"
//ORDER 
 export const ORDER_BY_NAME = "ORDER_BY_NAME"
 export const ASCENDENTE = "ASCENDENTE"
 export const DESCENDENTE = "DESCENDENTE"
 export const ORDER_BY_POPULATION = "ORBER_BY_POPULATION"
 export const HIGHER_POPULATION = "HIGHER_POPULATION"
 export const LESS_POPULATION = "LESS_POPULATION"
//ACTIVITES
export const GET_ACTIVITIES = "GET_ACTIVITIES"
export const POST_ACTIVITIES = "POST_ACTIVITIES"
// export const DELETE_ACTIVITIES = "DELETE_ACTIVITIES"
export const FILTER_BY_ACTIVITIES ="FILTER_BY_ACTIVITIES"
export const WINTER = "WINTER"
export const AUTUMN = "AUTUMN"
export const SPRING = "SPRING"
export const SUMMER = "SUMMER"
